/**
 * Solar 图标集（broken）—— 「Solar 断续线」图标主题
 *
 * 设计语言：Solar Broken：描边在转折处断开留白，笔触速写感最强，与任何连续描边图标集都不会混淆。
 * 来源：@solar-icons/react 的 broken 风格（图标由 480 Design 设计，CC BY 4.0；代码 MIT）。
 * 覆盖：60/62 语义名；github / twitter 在该图标集中无对应图形，由 withLucideFallback 回退 Lucide。
 *
 * Props 适配：见 icons-adapters 的 strokeIcon（size + strokeWidth 透传）。
 */

import {
  AddCircleIcon,
  AlignBottomIcon,
  AlignHorizontalSpacingIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignTopIcon,
  AlignVerticalSpacingIcon,
  AltArrowDownIcon,
  AltArrowRightIcon,
  ArchiveMinimalisticIcon,
  ArrowLeftIcon,
  ArrowRightUpIcon,
  BookIcon,
  BookmarkIcon,
  CheckCircleIcon,
  ClockCircleIcon,
  CloseCircleIcon,
  CropIcon,
  DocumentTextIcon,
  DoubleAltArrowLeftIcon,
  DoubleAltArrowRightIcon,
  EyeClosedIcon,
  EyeIcon,
  FeedIcon,
  FolderIcon,
  GalleryIcon,
  GalleryWideIcon,
  HeartIcon,
  InboxIcon,
  InfoCircleIcon,
  KeyboardIcon,
  LayersMinimalisticIcon,
  LetterOpenedIcon,
  LinkIcon,
  ListIcon,
  MagicWandIcon,
  MagnifierIcon,
  MaximizeIcon,
  MicrophoneIcon,
  MinusCircleIcon,
  MusicNoteIcon,
  PaletteIcon,
  PaperclipIcon,
  PenIcon,
  PlaneIcon,
  PulseIcon,
  QuoteIcon,
  RefreshIcon,
  SettingsIcon,
  ShuffleIcon,
  StarIcon,
  TableIcon,
  TagIcon,
  TextFieldIcon,
  TrashBinTrashIcon,
  UndoLeftIcon,
  UploadIcon,
  VideoFrameIcon,
  WidgetIcon
} from '@solar-icons/react/broken'
import { strokeIcon } from './icons-adapters'
import { withLucideFallback, type IconThemeMap } from './icon-themes'

/** Solar 断续线：线条断开留白，像手绘草稿 */
const PARTIAL: Partial<IconThemeMap> = {
  rss: strokeIcon(FeedIcon),
  read: strokeIcon(LetterOpenedIcon),
  inbox: strokeIcon(InboxIcon),
  later: strokeIcon(ClockCircleIcon),
  favorite: strokeIcon(StarIcon),
  archived: strokeIcon(ArchiveMinimalisticIcon),
  all: strokeIcon(LayersMinimalisticIcon),
  podcast: strokeIcon(MicrophoneIcon),
  video: strokeIcon(VideoFrameIcon),
  settings: strokeIcon(SettingsIcon),
  search: strokeIcon(MagnifierIcon),
  gallery: strokeIcon(GalleryIcon),
  board: strokeIcon(WidgetIcon),
  writer: strokeIcon(DocumentTextIcon),
  plus: strokeIcon(AddCircleIcon),
  refresh: strokeIcon(RefreshIcon),
  type: strokeIcon(TextFieldIcon),
  link: strokeIcon(LinkIcon),
  image: strokeIcon(GalleryWideIcon),
  file: strokeIcon(PaperclipIcon),
  ref: strokeIcon(QuoteIcon),
  minus: strokeIcon(MinusCircleIcon),
  close: strokeIcon(CloseCircleIcon),
  edit: strokeIcon(PenIcon),
  eyeOff: strokeIcon(EyeClosedIcon),
  eye: strokeIcon(EyeIcon),
  bookmark: strokeIcon(BookmarkIcon),
  send: strokeIcon(PlaneIcon),
  tag: strokeIcon(TagIcon),
  trash: strokeIcon(TrashBinTrashIcon),
  check: strokeIcon(CheckCircleIcon),
  external: strokeIcon(ArrowRightUpIcon),
  chevronDown: strokeIcon(AltArrowDownIcon),
  chevronRight: strokeIcon(AltArrowRightIcon),
  upload: strokeIcon(UploadIcon),
  book: strokeIcon(BookIcon),
  palette: strokeIcon(PaletteIcon),
  music: strokeIcon(MusicNoteIcon),
  keyboard: strokeIcon(KeyboardIcon),
  undo: strokeIcon(UndoLeftIcon),
  info: strokeIcon(InfoCircleIcon),
  activity: strokeIcon(PulseIcon),
  list: strokeIcon(ListIcon),
  rows: strokeIcon(TableIcon),
  panelLeftClose: strokeIcon(DoubleAltArrowLeftIcon),
  panelLeftOpen: strokeIcon(DoubleAltArrowRightIcon),
  heart: strokeIcon(HeartIcon),
  sparkles: strokeIcon(MagicWandIcon),
  alignLeft: strokeIcon(AlignLeftIcon),
  alignRight: strokeIcon(AlignRightIcon),
  alignTop: strokeIcon(AlignTopIcon),
  alignBottom: strokeIcon(AlignBottomIcon),
  distributeH: strokeIcon(AlignHorizontalSpacingIcon),
  distributeV: strokeIcon(AlignVerticalSpacingIcon),
  star: strokeIcon(StarIcon),
  maximize: strokeIcon(MaximizeIcon),
  frame: strokeIcon(CropIcon),
  folder: strokeIcon(FolderIcon),
  shuffle: strokeIcon(ShuffleIcon),
  arrowLeft: strokeIcon(ArrowLeftIcon)
}

export const SOLAR_BROKEN_ICON_MAP: IconThemeMap = withLucideFallback(PARTIAL)
