/**
 * IBM Carbon 图标集 —— 「直角企业」图标主题
 *
 * 设计语言：IBM Carbon Design System 的 16px 图形语言 —— 全直角端点的实心路径、
 * 严格 2px 对齐网格、无圆角无描边，密度与秩序感最强，与任何圆润系图标集形成最大反差。
 * 来源：@carbon/icons-react（Apache-2.0，IBM 出品）。
 * 覆盖：62/62 语义名，无回退。
 *
 * Props 适配：见 icons-adapters 的 sizedIcon（图形为固定路径，只透传 size）。
 */

import {
  Activity,
  Add,
  AlignHorizontalLeft,
  AlignHorizontalRight,
  AlignVerticalBottom,
  AlignVerticalTop,
  Archive,
  ArrowLeft,
  ArrowUpRight,
  Attachment,
  Book,
  Bookmark,
  Checkmark,
  ChevronDown,
  ChevronRight,
  Close,
  ColorPalette,
  Crop,
  Dashboard,
  DistributeHorizontalCenter,
  DistributeVerticalCenter,
  DocumentBlank,
  Edit,
  Email,
  Favorite,
  FavoriteFilled,
  Folder,
  Grid,
  Image,
  ImageCopy,
  Information,
  Keyboard,
  Link,
  List,
  LogoGithub,
  LogoX,
  MagicWand,
  MailAll,
  Maximize,
  Microphone,
  Music,
  Quotes,
  Renew,
  Row,
  Rss,
  Search,
  SendAlt,
  Settings,
  Shuffle,
  SidePanelClose,
  SidePanelOpen,
  Star,
  Subtract,
  Tag,
  TextFont,
  Time,
  TrashCan,
  Undo,
  Upload,
  Video,
  View,
  ViewOff
} from '@carbon/icons-react'
import { sizedIcon } from './icons-adapters'
import { withLucideFallback, type IconThemeMap } from './icon-themes'

/** 直角企业：直角端点、实心路径、严格网格 */
const PARTIAL: Partial<IconThemeMap> = {
  rss: sizedIcon(Rss),
  read: sizedIcon(Email),
  inbox: sizedIcon(MailAll),
  later: sizedIcon(Time),
  favorite: sizedIcon(FavoriteFilled),
  archived: sizedIcon(Archive),
  all: sizedIcon(Grid),
  podcast: sizedIcon(Microphone),
  video: sizedIcon(Video),
  settings: sizedIcon(Settings),
  search: sizedIcon(Search),
  gallery: sizedIcon(Image),
  board: sizedIcon(Dashboard),
  writer: sizedIcon(DocumentBlank),
  plus: sizedIcon(Add),
  refresh: sizedIcon(Renew),
  type: sizedIcon(TextFont),
  link: sizedIcon(Link),
  image: sizedIcon(ImageCopy),
  file: sizedIcon(Attachment),
  ref: sizedIcon(Quotes),
  minus: sizedIcon(Subtract),
  close: sizedIcon(Close),
  edit: sizedIcon(Edit),
  eyeOff: sizedIcon(ViewOff),
  eye: sizedIcon(View),
  bookmark: sizedIcon(Bookmark),
  send: sizedIcon(SendAlt),
  tag: sizedIcon(Tag),
  trash: sizedIcon(TrashCan),
  check: sizedIcon(Checkmark),
  external: sizedIcon(ArrowUpRight),
  chevronDown: sizedIcon(ChevronDown),
  chevronRight: sizedIcon(ChevronRight),
  upload: sizedIcon(Upload),
  book: sizedIcon(Book),
  github: sizedIcon(LogoGithub),
  twitter: sizedIcon(LogoX),
  palette: sizedIcon(ColorPalette),
  music: sizedIcon(Music),
  keyboard: sizedIcon(Keyboard),
  undo: sizedIcon(Undo),
  info: sizedIcon(Information),
  activity: sizedIcon(Activity),
  list: sizedIcon(List),
  rows: sizedIcon(Row),
  panelLeftClose: sizedIcon(SidePanelClose),
  panelLeftOpen: sizedIcon(SidePanelOpen),
  heart: sizedIcon(Favorite),
  sparkles: sizedIcon(MagicWand),
  alignLeft: sizedIcon(AlignHorizontalLeft),
  alignRight: sizedIcon(AlignHorizontalRight),
  alignTop: sizedIcon(AlignVerticalTop),
  alignBottom: sizedIcon(AlignVerticalBottom),
  distributeH: sizedIcon(DistributeHorizontalCenter),
  distributeV: sizedIcon(DistributeVerticalCenter),
  star: sizedIcon(Star),
  maximize: sizedIcon(Maximize),
  frame: sizedIcon(Crop),
  folder: sizedIcon(Folder),
  shuffle: sizedIcon(Shuffle),
  arrowLeft: sizedIcon(ArrowLeft)
}

export const CARBON_ICON_MAP: IconThemeMap = withLucideFallback(PARTIAL)
