/**
 * Phosphor 图标集 —— 「双色调」与「实心」两套图标主题
 *
 * 设计语言：圆润几何 + 统一 256px 网格；同一组件通过 weight 切换风格。
 * - duotone：主体实色 + 同色 20% 填充底块，识别度最高，层次感强
 * - fill：纯实心色块，与 Lucide / Tabler 的线性形成最强对比
 *
 * Props 适配：业务层统一传 size / strokeWidth，此处只取 size，weight 由主题固定。
 */

import {
  AlignBottom,
  AlignLeft,
  AlignRight,
  AlignTop,
  Archive,
  ArrowLeft,
  ArrowUUpLeft,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsHorizontal,
  ArrowsOut,
  ArrowsVertical,
  BookOpen,
  Bookmark,
  Books,
  CaretDown,
  CaretRight,
  Check,
  Clock,
  Crop,
  EnvelopeOpen,
  Eye,
  EyeClosed,
  FileText,
  Folder,
  Gear,
  GithubLogo,
  Heart,
  Image,
  Info,
  Keyboard,
  Layout,
  Link,
  List,
  MagnifyingGlass,
  Microphone,
  Minus,
  MusicNote,
  Palette,
  PaperPlane,
  Paperclip,
  Pencil,
  Plus,
  Pulse,
  Quotes,
  Rows,
  Rss,
  Shuffle,
  Sidebar,
  SidebarSimple,
  Sparkle,
  Star,
  Tag,
  TextAa,
  Trash,
  Tray,
  Upload,
  Video,
  X,
  XLogo
} from '@phosphor-icons/react'
import { withLucideFallback, type IconComponent, type IconThemeMap } from './icon-themes'

type Props = React.ComponentProps<IconComponent>

function P(C: React.ComponentType<Record<string, unknown>>, weight: 'duotone' | 'fill'): IconComponent {
  const Wrapped = ({ size = 24, className, style, ...rest }: Props) => (
    <C size={size} weight={weight} className={className} style={style} {...rest} />
  )
  Wrapped.displayName = weight === 'duotone' ? 'PhosphorDuotone' : 'PhosphorFill'
  return Wrapped as IconComponent
}

/** 双色调映射 */
const PHOSPHOR_DUOTONE_PARTIAL: Partial<IconThemeMap> = {
  rss: P(Rss, 'duotone'),
  read: P(EnvelopeOpen, 'duotone'),
  inbox: P(Tray, 'duotone'),
  later: P(Clock, 'duotone'),
  favorite: P(Star, 'duotone'),
  archived: P(Archive, 'duotone'),
  all: P(Books, 'duotone'),
  podcast: P(Microphone, 'duotone'),
  video: P(Video, 'duotone'),
  settings: P(Gear, 'duotone'),
  search: P(MagnifyingGlass, 'duotone'),
  gallery: P(Image, 'duotone'),
  board: P(Layout, 'duotone'),
  writer: P(FileText, 'duotone'),
  plus: P(Plus, 'duotone'),
  refresh: P(ArrowsClockwise, 'duotone'),
  type: P(TextAa, 'duotone'),
  link: P(Link, 'duotone'),
  image: P(Image, 'duotone'),
  file: P(Paperclip, 'duotone'),
  ref: P(Quotes, 'duotone'),
  minus: P(Minus, 'duotone'),
  close: P(X, 'duotone'),
  edit: P(Pencil, 'duotone'),
  eyeOff: P(EyeClosed, 'duotone'),
  eye: P(Eye, 'duotone'),
  bookmark: P(Bookmark, 'duotone'),
  send: P(PaperPlane, 'duotone'),
  tag: P(Tag, 'duotone'),
  trash: P(Trash, 'duotone'),
  check: P(Check, 'duotone'),
  external: P(ArrowUpRight, 'duotone'),
  chevronDown: P(CaretDown, 'duotone'),
  chevronRight: P(CaretRight, 'duotone'),
  upload: P(Upload, 'duotone'),
  book: P(BookOpen, 'duotone'),
  github: P(GithubLogo, 'duotone'),
  twitter: P(XLogo, 'duotone'),
  palette: P(Palette, 'duotone'),
  music: P(MusicNote, 'duotone'),
  keyboard: P(Keyboard, 'duotone'),
  undo: P(ArrowUUpLeft, 'duotone'),
  info: P(Info, 'duotone'),
  activity: P(Pulse, 'duotone'),
  list: P(List, 'duotone'),
  rows: P(Rows, 'duotone'),
  panelLeftClose: P(SidebarSimple, 'duotone'),
  panelLeftOpen: P(Sidebar, 'duotone'),
  heart: P(Heart, 'duotone'),
  sparkles: P(Sparkle, 'duotone'),
  alignLeft: P(AlignLeft, 'duotone'),
  alignRight: P(AlignRight, 'duotone'),
  alignTop: P(AlignTop, 'duotone'),
  alignBottom: P(AlignBottom, 'duotone'),
  distributeH: P(ArrowsHorizontal, 'duotone'),
  distributeV: P(ArrowsVertical, 'duotone'),
  star: P(Star, 'duotone'),
  maximize: P(ArrowsOut, 'duotone'),
  frame: P(Crop, 'duotone'),
  folder: P(Folder, 'duotone'),
  shuffle: P(Shuffle, 'duotone'),
  arrowLeft: P(ArrowLeft, 'duotone')
}

/** 实心映射（与双色调共用图形，仅权重不同） */
const PHOSPHOR_FILL_PARTIAL: Partial<IconThemeMap> = {
  rss: P(Rss, 'fill'),
  read: P(EnvelopeOpen, 'fill'),
  inbox: P(Tray, 'fill'),
  later: P(Clock, 'fill'),
  favorite: P(Star, 'fill'),
  archived: P(Archive, 'fill'),
  all: P(Books, 'fill'),
  podcast: P(Microphone, 'fill'),
  video: P(Video, 'fill'),
  settings: P(Gear, 'fill'),
  search: P(MagnifyingGlass, 'fill'),
  gallery: P(Image, 'fill'),
  board: P(Layout, 'fill'),
  writer: P(FileText, 'fill'),
  plus: P(Plus, 'fill'),
  refresh: P(ArrowsClockwise, 'fill'),
  type: P(TextAa, 'fill'),
  link: P(Link, 'fill'),
  image: P(Image, 'fill'),
  file: P(Paperclip, 'fill'),
  ref: P(Quotes, 'fill'),
  minus: P(Minus, 'fill'),
  close: P(X, 'fill'),
  edit: P(Pencil, 'fill'),
  eyeOff: P(EyeClosed, 'fill'),
  eye: P(Eye, 'fill'),
  bookmark: P(Bookmark, 'fill'),
  send: P(PaperPlane, 'fill'),
  tag: P(Tag, 'fill'),
  trash: P(Trash, 'fill'),
  check: P(Check, 'fill'),
  external: P(ArrowUpRight, 'fill'),
  chevronDown: P(CaretDown, 'fill'),
  chevronRight: P(CaretRight, 'fill'),
  upload: P(Upload, 'fill'),
  book: P(BookOpen, 'fill'),
  github: P(GithubLogo, 'fill'),
  twitter: P(XLogo, 'fill'),
  palette: P(Palette, 'fill'),
  music: P(MusicNote, 'fill'),
  keyboard: P(Keyboard, 'fill'),
  undo: P(ArrowUUpLeft, 'fill'),
  info: P(Info, 'fill'),
  activity: P(Pulse, 'fill'),
  list: P(List, 'fill'),
  rows: P(Rows, 'fill'),
  panelLeftClose: P(SidebarSimple, 'fill'),
  panelLeftOpen: P(Sidebar, 'fill'),
  heart: P(Heart, 'fill'),
  sparkles: P(Sparkle, 'fill'),
  alignLeft: P(AlignLeft, 'fill'),
  alignRight: P(AlignRight, 'fill'),
  alignTop: P(AlignTop, 'fill'),
  alignBottom: P(AlignBottom, 'fill'),
  distributeH: P(ArrowsHorizontal, 'fill'),
  distributeV: P(ArrowsVertical, 'fill'),
  star: P(Star, 'fill'),
  maximize: P(ArrowsOut, 'fill'),
  frame: P(Crop, 'fill'),
  folder: P(Folder, 'fill'),
  shuffle: P(Shuffle, 'fill'),
  arrowLeft: P(ArrowLeft, 'fill')
}

export const PHOSPHOR_DUOTONE_ICON_MAP: IconThemeMap = withLucideFallback(PHOSPHOR_DUOTONE_PARTIAL)
export const PHOSPHOR_FILL_ICON_MAP: IconThemeMap = withLucideFallback(PHOSPHOR_FILL_PARTIAL)
